import torch
import esm
import numpy
model, alphabet = esm.pretrained.esm2_t6_8M_UR50D()
model.num_layers = 6
model.embed_dim = 320
model.attention_heads = 20
batch_converter = alphabet.get_batch_converter()
model.eval()
data = []
data.append(("seq1", "MKPRIVLKSSSLMPSWDRPVLPGAPGCELAGGVARAHPIKHGVVVDWDALEGLWERLMVGGLQVHPEQWPVLVSDSPSAPPKGREKVAELLFEALTVPACHMANTALLALCSIGAFSGLAVEAGAGVCHATPIYAGHSWHKATFRLNVAGSTLSRYFRDLLVAACPDLQLQGLSRKTVTQLKKRCCYVSLDFQGDICDPARHQRACFCLGNGCYVRLGSERFRCPEPIFQPSLLGHPEPGLPTLAFQALQKIPTTLRTRLANTVVLAGGSTLFPGFVERMNLELEAQCRRHGYPALQPCLVAHPGRDTAVWTGGSMMASLNSFQCRWMTRAMYQEHGPLLVRDVFD"))
batch_labels, batch_strs, batch_tokens = batch_converter(data)
